### ISSUE TITLE
White Screen (IN WINDOWS)

### ISSUE THREAD

**Issue by TheRodrixHD** [montoyo/mcef#87]
How I can fix this

**Comment by da5hu** [comment]
hey, I had the same issue. Turns out you need to get version 1.12.2 of MCEF, you need to get only that version in order for it to work.
official page for MCEF: https://montoyo.net/wd3/?modid=mcef
(by the way the mod version must be higher than 0.9, so you will either get 1.11 or 1.11b. *I got 1.11b)

**Comment by da5hu** [comment]
> How I can fix this
hey, I had the same issue. Turns out you need to get version 1.12.2 of MCEF, you need to get only that version in order for it to work.
official page for MCEF: https://montoyo.net/wd3/?modid=mcef
(by the way the mod version must be higher than 0.9, so you will either get 1.11 or 1.11b. *I got 1.11b)
